version: '3.7'

services:
#  fc_app:
#    build: .
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./:/app
#    working_dir: /app
#    command: ./gradlew bootRun
#    networks:
#      - fc_network
#    depends_on:
#      - fc_mysql

  mysql:
    container_name: adm_videos_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=adm_videos
      #- MYSQL_USER=root
      - MYSQL_PASSWORD=root
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    networks:
      - adm_videos_network

networks:
  adm_videos_network:
