server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html, text/css, text/javascript, application/javascript, application/json, application/xml, application/x-javascript
    min-response-size: 1024

spring:
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.schema}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${mysql.username}
    password: ${mysql.password}
    hikari:
      auto-commit: false
      connection-timeout: 250 # Ideal manter um valor baixo
      max-lifetime: 600000 #Tempo max que uma conexão pode ficar aberta
      maximum-pool-size: 20 #Não deve ser muito alto pois pode sobrecarregar o banco de dados
      minimum-idle: 10
      pool-name: master

  jpa:
    open-in-view: false
    show-sql: 'true'
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.MySQL5Dialect
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
    hibernate:
      ddl-auto: update
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER