spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: root
    url: jdbc:h2:mem:adm_videos;MODE=MySQL;DATABASE_TO_LOWER=TRUE
  jpa:
    open-in-view: false
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2